### ISSUE TITLE
in production

### ISSUE THREAD

**Issue by RDP1974** [IBSurgeon/lucene_udr#1]
hi,
please can I ask if you have real production software with this extension?
it is reliable, safe, scalable?
thanks

**Comment by sim1984** [comment]
It is used in 50Gb database with addresses search, very fast, 30ms vs 10sec of usual search.
Approximately 50 users are working on the address database, but there are no updates. Our extension does not do real-time index updates. All index updates are deferred. We can do an index update either through a full rebuild, or according to the change log with the accumulation of changes in triggers and launching the update procedure from these logs on a schedule.

**Comment by sim1984** [comment]
Please do not write questions not related to bugs and improvements in issue. There is a channel for discussion https://t.me/+2bn6m3vWV7thZTBi
or support@ib-aid.com

**Comment by RDP1974** [comment]
Hello,
how much time is needed to rebuild the words index? Approximately
thanks

Da: Simonov Denis ***@***.***>
Inviato: martedì 5 luglio 2022 11:49
A: IBSurgeon/lucene_udr ***@***.***>
Cc: Roberto Della Pasqua ***@***.***>; Author ***@***.***>
Oggetto: Re: [IBSurgeon/lucene_udr] in production (Issue #1)


It is used in 50Gb database with addresses search, very fast, 30ms vs 10sec of usual search.
Approximately 50 users are working on the address database, but there are no updates. Our extension does not do real-time index updates. All index updates are deferred. We can do an index update either through a full rebuild, or according to the change log with the accumulation of changes in triggers and launching the update procedure from these logs on a schedule.

-
