### ISSUE TITLE
Firebird 5?

### ISSUE THREAD

**Issue by ghost** [IBSurgeon/lucene_udr#10]
Does this work in the newly released Firebird 5? The Firebird website still says the following, so I was unsure:
> Users of Firebird 3 and 4 can use free open source [IBSurgeon FTS UDR library](https://github.com/IBSurgeon/lucene_udr) to implement full text search procedures

**Comment by sim1984** [comment]
In my personal project, LuceneUDR works great with Firebird 5.0.

**Comment by ghost** [comment]
Ok, thanks! I wasn't sure if there were incompatibility issues introduced in Firebird 5 or not. I will update to Firebird 5 to see if it works in my case, and if it does, I'll close this issue. Thanks again.
