### ISSUE TITLE
Lucene version

### ISSUE THREAD

**Issue by livius2** [IBSurgeon/lucene_udr#8]
Hi

when i run 
`SELECT FTS$STATISTICS.FTS$LUCENE_VERSION () FROM RDB$DATABASE;`

i got `3.0.8`. Why it is so old, current one is `9.10.0`?

Or it is version of something else then lucene itself?

**Comment by sim1984** [comment]
1. Lucene written in Java is not the same as Lucene++
2. I updated the builds for Windows. Now
```
SELECT FTS$STATISTICS.FTS$LUCENE_VERSION () FROM RDB$DATABASE;
```
Returns `3.0.9`.

**Comment by livius2** [comment]
Ok, so this is version of `Lucene ++` not Apache Lucene.

Sorry for the off-topic question, but is Java not the same as Lucene? Does it not depend on the Java version and get updated when the Java version is updated? Or is 'Lucene' in the name just a coincidence? I am looking for polish language Analyzer.

P.S. thank you for updating to lucene++ 3.0.9.

**Comment by sim1984** [comment]
Lucene++ is a port of Lucene (Java) to C++. Unfortunately, it lags quite far behind the original Lucene.

**Comment by livius2** [comment]
So it is like Interbase and Firebird, they have same beginning, but they are separate now? 
Or it is only about frequence of updates?
